kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: development
  name: endpoints-list
rules:
- apiGroups: ["", extensions", "apps"]
  resources: ["endpoints"]
  verbs: ["list"]
