---
apiVersion: v1
kind: Pod
metadata:
  name: endpoints-pod
  labels:
    app: endpoints
  namespace: development
spec:
  serviceAccountName: endpoint-service-account
  containers:
    - name: endpoints
      image: endpoints/python:0.0.1
